# docker-compose.prod.yml
services:
  app:
    container_name: nest-app-prod
    build:
      context: .
      target: production
    env_file:
      - .env.production
    ports:
      - '9200:9200'
    restart: always
