on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744

      - name: login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-playground:latest .

      - name: push image to docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/multi-playground:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: pull image from docker hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/multi-playground:latest

      - name: delete old container
        run: docker rm -f multi-playground || true

      - name: run new container
        run: docker run -d -p 9200:9200 --name multi-playground ${{ secrets.DOCKER_USERNAME }}/multi-playground:latest